// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Model;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ContextoDB))]
    [Migration("20241103231249_init_db")]
    partial class init_db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiDrinkInTheHouse.Model.Bebida", b =>
                {
                    b.Property<int>("IDbebida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDbebida"));

                    b.Property<string>("BRAND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PORCENTAJE_ALC")
                        .HasColumnType("int");

                    b.Property<decimal>("PRECIO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RETORNABLE")
                        .HasColumnType("bit");

                    b.Property<int>("STOCK")
                        .HasColumnType("int");

                    b.Property<int>("VENVIDO")
                        .HasColumnType("int");

                    b.HasKey("IDbebida");

                    b.ToTable("Bebidas");
                });

            modelBuilder.Entity("ApiDrinkInTheHouse.Model.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("APELLIDO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FECHA_NAC")
                        .HasColumnType("datetime2");

                    b.Property<string>("NOMBRE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
